# ── Test Profile ──
spring.datasource.url=jdbc:tc:postgresql:17:///fortyeightid
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver

spring.flyway.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6370

spring.mail.host=localhost
spring.mail.port=1025

logging.level.io.k48.fortyeightid=DEBUG
